---
- hosts: digitaloceanservers
  remote_user: root
  sudo: yes

  roles:
    - common
    - php-fpm
    - memcached
    - percona
    - nginx
    - wp-cli
    - varnish
    # - { role: wordpress, enviro: hhvm, tags: [ 'wordpress' ] }
